AllCops:
  Exclude:
    - vendor/bundle/**/*
    - config.ru
    - db/*
    - db/*/**
    - config/*/**
    - config/*
    - lib/tasks/*
    - script/**
    - bin/**
    - spec/rails_helper.rb
    - spec/spec_helper.rb
AndOr:
  Enabled: false
BlockLength:
  Enabled: false
Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
